/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package favmovieapp;

import Repositories.MovieRepository;

import static jdk.internal.logger.DefaultLoggerFinder.SharedLoggers.system;

public class App {
    public static void main(String[] args) {
        MovieRepository movieRepository = new MovieRepository();
        MovieService movieService = new MovieService();
        MovieServer movieServer = new MovieServer();
        system.out.println(movies.getOriginal_title);
    }
}
