/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package favmovieapp;

import Repositories.MovieRepository;



public class App {
    public static void main(String[] args) {
        MovieRepository movieRepository = new MovieRepository();
        MovieService movieService = new MovieService();
        MovieServer movieServer = new MovieServer();

    }
}
